export default {
    "2dClick": "Main_Options_2d_click",
    "3dClick": "Main_Options_3d_click",
    "UGCClick": "Main_Options_UGC_click",
    "2dSubmit": "Main_Options_2d_submit",
    "3dSubmit": "Main_Options_3d_submit",
    "UGCSubmit": "Main_Options_UGC_submit",
    "swipe": "Main_Case-sudy_swipe",
    "marketingClick": "Main_Marketing videos_Get offer_click",
    "marketingSubmit": "Main_Marketing videos_Get offer_submit",
    "marketingDemoClick": "Main_Marketing videos_Get a demo_click",
    "seeItClick": "Main_See it for yourself_Get offer_click",
    "seeItSubmit": "Main_See it for yourself_Get offer_submit",
    "demoClick": "Main_reqest_demo_click",
};
